[package]
name = "npuzzle"
version = "0.1.0"
authors = ["Charles Gleason <cgleason@student.42.us.org>"]
edition = "2018"

[dependencies]
clap = "~2.32.0"
rand = "*"
piston = "0.38.0"
piston2d-graphics = "0.27.0"
pistoncore-glutin_window = "0.50.0"
piston2d-opengl_graphics = "0.55.0"
